genre:
  - "70s funk"
  - "P-funk"
  - "Nu disco"
  - "Lofi"
  - "Surf rock"
  - "Jazz"
  - "80s pop"
instrumentation:
  - "a clavinet"
  - "gated drums"
  - "congas and bongos"
  - "a synth with vibrato"
  - "a leslie speaker"
  - "a whistle line"
  - "a drum machine"
  - "a cheesy sax"
  - "plasticky keys"
time_signature:
  - "4/4"
  - "12/8"
effects:
  - "wah"
  - "phaser"
  - "tremolo"
  - "sweeping filter"
  - "ring modulator"
  - "reverb"
constraints:
  - "the bassline should stays constant in part A, follows chords in part B"
  - "use a drone throughout"
  - "create a breakdown section in half time"
  - "use an arpeggiator"
  - "use an augmented chord"
  - "use the BBC orchestra VST (free)"
  - "use Jacob Collier's Audience Choir VST (free)"
  - "reharm the melody in the bridge"
  - "sample a baby toy"
descriptors:
  - "with contrast"
  - "to be played in a modernist interior"
  - "to match a slow motion scene"
  - "muddy"
  - "silky"
  - "with a sense of urgency"
  - "with a sense of nostalgia"
  - "with a sense of unease"
  - "with a sense of space"
  - "cheesy"
  - "syncopated"
  - "shimmery"

